### ISSUE TITLE
不支持and or的联合查询

### ISSUE THREAD

**Issue by CasparLong** [liuyuyu/weekend#2]
像WHERE a='b' AND (c='d' or e='f')，需要配合Criteria，但是就不能用Lambada
还有order by也不支持Lambada

**Comment by onlyeat3** [comment]
基于通用mapper来的，or好像没办法支持。order by晚点我可以加上去

**Comment by onlyeat3** [comment]
@CasparLong 旧版本的通用mapper里直接打包的weekend，新版的直接把两个仓库合并了。issue转到通用mapper下面提吧。这个仓库我要关掉issue了
